//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControlAss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_details
    {
        public int product_id { get; set; }
        public int userid { get; set; }
        public string product_name { get; set; }
        public string category { get; set; }
        public long price { get; set; }
        public long quantity { get; set; }
        public string short_description { get; set; }
        public string long_description { get; set; }
        public string small_img { get; set; }
        public string large_img { get; set; }
    }
}
