//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using SourceControlAss.Comman;
namespace SourceControlAss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int id { get; set; }
        [Required]
        [StringLength(20, MinimumLength = 2)]
        public string name { get; set; }
        [Required]
        public string email { get; set; }
        [Required]
        public int age { get; set; }
        [Required]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/mm/yyyy}")]
        [DataType(DataType.Date)]
        public string dob { get; set; }
        [Required]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/mm/yyyy}")]
        [DataType(DataType.Date)]
        [DateValidation(ErrorMessage = "Sorry, the date can't be later than today's date")]
        public DateTime doj { get; set; }
    }
}
